version: '2.3'

services:
  main:
    container_name: CosPlace
    build:
      context: ./
      dockerfile: docker/Dockerfile
    runtime: nvidia
    restart: always
    env_file:
      - "docker/env.env"
    volumes:
      - "/media/mmlab/hdd:/hdd"
    expose:
      - "8000"
    ports:
      - "22000:22"
      - "22055:8000"
    ipc: host
    stdin_open: true
    tty: true
